bg_galaxy_file = None
strong_lensing_file = 'A370_silver_image_catalog_change_knot_length_final.txt'
interpol_size = 3000
sigma = 0.6
folder_path = './result_file50_a370_knot1'
result_fits = '/result_fits.fits'
input_fits = folder_path + '/initial_fits.fits'
cluster_z = 0.375
effect_source_red = 1
x1 = 0
y1 = 0
x2 = x1 + interpol_size
y2 = y1 + interpol_size
r_weight = 1
g_weight = 0
m_weight = 1
prior_reduce = 0.995
kapmap_size = 100
margin = 20
padding = int(2*margin + kapmap_size)
initial_kappa = 0.5
lower_kappa, upper_kappa = 0.01, 10
learn_rate = 5e-3
upper_red = 15
free_param_redshift_source = 8, 11, 41, 43, 44, 45

